### ISSUE TITLE
Android7 RPMsg issue to Download image from Kynetics server

### ISSUE THREAD

**Issue by neuberfran** [Kynetics/Android_AMP_IMU_PlotApp#1]
https://www.kynetics.com/android-bsp/toradex

I need help
To download image Colibri i.MX7D + Iris Carrier board
from the website mentioned above.

This project is important to me. I have a lot of knowledge of RPMsg and several imx7d boards here:

![Captura de tela de 2022-10-17 21-13-14](https://user-images.githubusercontent.com/38701397/198892698-13812563-a00c-4e6f-a5d2-e97acd188de5.png)

**Comment by diegorondini** [comment]
Hi Neuber,
we replied by email, and you solved it on your own, so we're closing this.
Regards

**Comment by neuberfran** [comment]
@diegorondini Sorry. There was a mistake and I still need this project


https://docs.google.com/document/d/1reCjHDlbP2q1NwDFXZw4vIujtxzkJJ93qIrgnJcuHEE/edit?usp=drivesdk

I Hope u jnderstand-me now
